sudo: required
services:
  - docker
language: python
python: "3.6"
install:
  - pip install -r src/requirements.txt
script:
  - src/manage.py test

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

