sudo: required
services:
  - docker
language: python
python: "3.6"
install:
  - pip install pipenv
  - cd src && pipenv install
script:
  - docker build -f Dockerfile.testing .
  - docker build -t registry.heroku.com/$HEROKU_APP/web -f Dockerfile.production .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

