sudo: required
services:
  - docker
language: python
python: "3.6"
script:
  - make test
  - make docker_build_prod
deploy:
  provider: script
  script: make docker_push_prod
  on:
    branch: master

