FROM python:3

ENV PYTHONUNBUFFERED 1

RUN pip install pipenv pycodestyle
ADD src /code/
ADD Makefile /code/
WORKDIR /code
RUN pipenv install --ignore-pipfile --system

RUN cd /code/ && make lint -e LINTROOT=.

RUN python3 /code/manage.py test
