# Generated by Django 2.0 on 2018-02-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180227_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidQuantity', models.IntegerField()),
                ('minimumQuantity', models.IntegerField()),
                ('product', models.ManyToManyField(to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PercentSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
