# Generated by Django 2.0 on 2018-03-01 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_packagedeal_percentsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='packageDeal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.PackageDeal'),
        ),
        migrations.AddField(
            model_name='product',
            name='percentSale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='products.PercentSale'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='pc', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unitPrice',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
