# Generated by Django 2.0 on 2018-03-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180301_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='organic',
            field=models.BooleanField(),
        ),
    ]
