# Generated by Django 2.0 on 2018-03-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('products', '0005_auto_20180301_1928'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='cart',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cart',
        ),
        migrations.AddField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(to='products.Order'),
        ),
        migrations.AlterField(
            model_name='packagedeal',
            name='minimumQuantity',
            field=models.IntegerField(verbose_name='Minimum quantity'),
        ),
        migrations.AlterField(
            model_name='packagedeal',
            name='paidQuantity',
            field=models.IntegerField(verbose_name='Paid quantity'),
        ),
        migrations.AlterField(
            model_name='percentsale',
            name='cut',
            field=models.IntegerField(verbose_name='Cut in percent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packageDeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='products.PackageDeal', verbose_name='Package-deal based sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='percentSale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='products.PercentSale', verbose_name='Percentage-based sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Price per product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=30, verbose_name='Unit type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unitPrice',
            field=models.FloatField(verbose_name='Unit price'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
    ]
