# Generated by Django 2.0 on 2018-03-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180302_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='notes',
        ),
    ]
