# Generated by Django 2.0 on 2018-03-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20180323_1344'),
        ('products', '0013_auto_20180323_1336'),
    ]

    operations = [
    ]
